version: "3.8"
services:
  wordpress:
    image: wordpress:php7.4-apache
    ports:
      - 30080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD_FILE: '/run/secrets/mysql-pwd'
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./mysql-pwd:/run/secrets/mysql-pwd
      - ./wordpress:/var/www/html
    depends_on:
      - "mysql"
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-pwd
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql-pwd:/run/secrets/mysql-pwd
      - ./mysql:/var/lib/mysql
