CREATE DATABASE IF NOT EXISTS `idoe_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER 'idoe'@'127.0.0.1' IDENTIFIED BY 'O8zwJ15Jdo42bAGIYY6+PA==';
GRANT ALL PRIVILEGES ON idoe_db.* TO 'idoe'@'127.0.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;